version: '3'
services:
        mysql:
                image: mysql:5.7
                container_name: mysql
                ports:
                        - "3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_DATABASE=ghost
                        - MYSQL_USER=ghost
                        - MYSQL_PASSWORD=password
        ghost:
                build: .
                container_name: ghost
                depends_on:
                        - mysql
                ports:
                        - "80:2368"
                restart: on-failure
